/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StudentManagement;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class TDstudentinfo extends javax.swing.JFrame {

    /**
     * Creates new form TDstudentinfo
     */
    public TDstudentinfo() {
        initComponents();
    }

    public void sett(String t) {
        jLabel3.setText(t.substring(0, 3));
        jLabel8.setText(t);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("studentinfo(担当先生)");

        jButton1.setText("戻る");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("削除");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("ＩＤ");

        jLabel2.setText("クラス");

        jLabel4.setText("お名前");

        jLabel5.setText("性別");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("男性");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("女性");

        jLabel6.setText("パスワード");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "クラス", "お名前", "性別", "パスワード"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("更新");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("追加");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("検索");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jButton3))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jRadioButton2)
                                    .addComponent(jRadioButton1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButton1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton1)
                                .addComponent(jButton2)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jRadioButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Teacher t = new Teacher();
        t.set(jLabel8.getText());
        this.dispose();
        t.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        TeachersLoad tl = new TeachersLoad();
        if (jTextField1.getText().isEmpty()) {
            jLabel7.setText("IDなし");
        } else {
            tl.setId(Integer.valueOf(jTextField1.getText()));
        }

        if (jTextField2.getText().isEmpty()) {
            jLabel7.setText("お名前入力なし");
        } else {
            tl.setName(jTextField2.getText());
        }

        tl.setKurasu(jLabel3.getText());
        tl.setPassword(jTextField1.getText());
        if (!jRadioButton1.isSelected() && !jRadioButton2.isSelected()) {
            jLabel7.setText("性別が選択していません");
            return;
        } else if (jRadioButton1.isSelected()) {
            tl.setSex(jRadioButton1.getText());
        } else if (!jRadioButton2.getHideActionText()) {
            tl.setSex(jRadioButton2.getText());
        }
//        jRadioButton.getText();
        List<TeachersLoad> tlo = new ArrayList<>();
        tlo.add(tl);
        Dbstudentinfo db = new Dbstudentinfo();
        try {
            db.getDBcon();
            int result;
            result = db.selectsinfo(tl.getId());
            if (result == 1) {
                jLabel7.setText("ID重複");
            } else if (tl.getId() < 1010000 || tl.getId() > 9999999) {
                jLabel7.setText("ID範囲外");
            } else {
                db.addLoad(tl);
                db.addstudentinfo(tl);
                db.addseiseki(tl);
                db.closeDBcon();
                jLabel7.setText("追加完了");
                if (!tlo.isEmpty()) {
                    DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
//            tableModel.setRowCount(0);
                    for (TeachersLoad t : tlo) {
                        tableModel.addRow(new Object[]{t.getId(), t.getKurasu(), t.getName(), t.getSex(), t.getPassword()});
                    }
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tstudentinfo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Tstudentinfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        TeachersLoad tl = new TeachersLoad();
        List<TeachersLoad> tlo = new ArrayList();
        tl.setId(Integer.valueOf(jTextField1.getText()));
        tl.setName(jTextField2.getText());
        tl.setKurasu(jLabel3.getText());
        if (jRadioButton1.isSelected()) {
            tl.setSex(jRadioButton1.getText());
        } else if (!jRadioButton2.getHideActionText()) {
            tl.setSex(jRadioButton2.getText());
        }
        tl.setPassword(jTextField3.getText());
        tlo.add(tl);
        Dbstudentinfo db = new Dbstudentinfo();
        try {
            db.getDBcon();
            db.updatestudentinfo(tl);
            db.updateload(tl);
            db.closeDBcon();
            if (!tlo.isEmpty()) {
                DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
                tableModel.setRowCount(0);
                for (TeachersLoad t : tlo) {
                    tableModel.addRow(new Object[]{t.getId(), t.getKurasu(), t.getName(), t.getSex(), t.getPassword()});
                    jLabel7.setText("更新完了");
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tstudentinfo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Tstudentinfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        jTextField1.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        jTextField2.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
        jTextField3.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        TeachersLoad slo = new TeachersLoad();
        if (!jTextField1.getText().isEmpty()) {
            slo.setId(Integer.valueOf(jTextField1.getText()));
        }
        slo.setName(jTextField2.getText());
        slo.setKurasu(jLabel3.getText());
        Dbstudentinfo db = new Dbstudentinfo();
        List<TeachersLoad> sload = new ArrayList();
//id !null
        if (!jTextField1.getText().isEmpty()) {
            if (slo.getName().isEmpty()) {
                try {
                    //            根据ID从数据库匹配
                    db.getDBcon();
                    sload = db.liketsinfoid(slo.getId());
                    if (sload.isEmpty()) {
                        jLabel7.setText("検索IDなし");
                    } else {
                        db.closeDBcon();
                        jLabel7.setText("検索完了");
//                     if (!sload.isEmpty()) {
                        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
                        tableModel.setRowCount(0);
                        for (TeachersLoad t : sload) {
                            tableModel.addRow(new Object[]{t.getId(), t.getKurasu(), t.getName(), t.getSex(), t.getPassword()});
                        }
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Tstudentinfo.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Tstudentinfo.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                try {
                    //                根据取到的ID和name去数据库匹配
                    db.getDBcon();
                    sload = db.likesinfo(slo.getId(), slo.getName());
                    if (sload.isEmpty()) {
                        jLabel7.setText("検索エラー");
                    } else {
                        db.closeDBcon();
                        jLabel7.setText("検索完了");
//                      if (!sload.isEmpty()) {
                        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
                        tableModel.setRowCount(0);
                        for (TeachersLoad t : sload) {
                            tableModel.addRow(new Object[]{t.getId(), t.getKurasu(), t.getName(), t.getSex(), t.getPassword()});
                        }
//            }

                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Tstudentinfo.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Tstudentinfo.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

//           id null
        } else if (jTextField1.getText().isEmpty()) {
//            name !null
            if (!slo.getName().isEmpty()) {
                try {
                    //              根绝name从数据库
                    db.getDBcon();
                    sload = db.likesinfo(slo.getName());
                    if (sload.isEmpty()) {
                        jLabel7.setText("検索nameなし");
                    } else {
                        db.closeDBcon();
                        jLabel7.setText("検索完了");
//                      if (!sload.isEmpty()) {
                        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
                        tableModel.setRowCount(0);
                        for (TeachersLoad t : sload) {
                            tableModel.addRow(new Object[]{t.getId(), t.getKurasu(), t.getName(), t.getSex(), t.getPassword()});
                        }
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Tstudentinfo.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Tstudentinfo.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                try {
                    //                根据class从数据库
                    db.getDBcon();
                    sload = db.selectstudentkurasu(slo.getKurasu());
                    db.closeDBcon();
                    jLabel7.setText("検索完了");
                    if (!sload.isEmpty()) {
                        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
                        tableModel.setRowCount(0);
                        for (TeachersLoad t : sload) {
                            tableModel.addRow(new Object[]{t.getId(), t.getKurasu(), t.getName(), t.getSex(), t.getPassword()});
                        }
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Tstudentinfo.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Tstudentinfo.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        TeachersLoad tload = new TeachersLoad();
        if (!jTextField1.getText().isEmpty()) {
            tload.setId(Integer.valueOf(jTextField1.getText()));
        }
        Dbstudentinfo db = new Dbstudentinfo();
        int result;
        try {
            db.getDBcon();
            result = db.selectsinfo(tload.getId());
            if (result == 1) {
                db.deletestudentinfo(tload.getId());
                db.deletelogin(tload.getId());
                db.closeDBcon();
                DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
                tableModel.removeRow(jTable1.getSelectedRow());
                jLabel7.setText("削除しました");
            } else {
                jLabel7.setText("IDユーザーが存在していません");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tstudentinfo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Tstudentinfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TDstudentinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TDstudentinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TDstudentinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TDstudentinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TDstudentinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
