/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StudentManagement;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Tstudentinfo extends javax.swing.JFrame {

    /**
     * Creates new form Ｔｓｔｕｄｅｎｔｉｎｆｏ
     */
    public Tstudentinfo() {
        initComponents();
    }

    public void set(String t) {
        jComboBox1.setSelectedItem(t);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choice1 = new java.awt.Choice();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jToggleButton1 = new javax.swing.JToggleButton();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("studentinfo(管理者)");

        jLabel1.setText("ID");

        jLabel2.setText("クラス");

        jLabel3.setText("お名前");

        jLabel4.setText("性別");

        jButton1.setText("更新");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("追加");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ＩＤ", "クラス", "お名前", "性別", "パスワード"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setText("パスワード");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("男性");

        buttonGroup1.add(jRadioButton);
        jRadioButton.setText("女性");

        jButton4.setText("戻る");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("検索");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton3.setText("削除");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "101", "102", "103", "104" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jRadioButton1)
                                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jRadioButton)
                                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton5))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                                .addComponent(jButton3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Teacher t = new Teacher();
        this.dispose();
        t.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /*
    追加
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        TeachersLoad tl = new TeachersLoad();
        if (jTextField1.getText().isEmpty()) {
            jLabel6.setText("IDなし");
        } else {

            tl.setId(Integer.valueOf(jTextField1.getText()));
        }

        if (jTextField3.getText().isEmpty()) {
            jLabel6.setText("お名前入力なし");
        } else {
            tl.setName(jTextField3.getText());
        }

        tl.setKurasu((String) jComboBox1.getSelectedItem());
        tl.setPassword(jTextField1.getText());
        if (!jRadioButton1.isSelected() && !jRadioButton.isSelected()) {
            jLabel6.setText("性別が選択していません");
            return;
        } else if (jRadioButton1.isSelected()) {
            tl.setSex(jRadioButton1.getText());
        } else if (!jRadioButton.getHideActionText()) {
            tl.setSex(jRadioButton.getText());
        }
//        jRadioButton.getText();
        List<TeachersLoad> tlo = new ArrayList<>();
        tlo.add(tl);
        Dbstudentinfo db = new Dbstudentinfo();
        try {
            db.getDBcon();
            int result;
            result = db.selectsinfo(tl.getId());
            if (result == 1) {
                jLabel6.setText("ID重複");
            } else if (tl.getId() < 1010000 || tl.getId() > 9999999) {
                jLabel6.setText("ID範囲外");
            } else if (!jTextField1.getText().substring(0, 3).equals(jComboBox1.getSelectedItem())) {
                jLabel6.setText("IDとクラスが合わない");
            } else {
                db.addLoad(tl);
                db.addstudentinfo(tl);
                db.addseiseki(tl);
                db.closeDBcon();
                jLabel6.setText("追加完了");
                if (!tlo.isEmpty()) {
                    DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
//            tableModel.setRowCount(0);
                    for (TeachersLoad t : tlo) {
                        tableModel.addRow(new Object[]{t.getId(), t.getKurasu(), t.getName(), t.getSex(), t.getPassword()});
                    }
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tstudentinfo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Tstudentinfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if (!jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString().isEmpty()) {
            jTextField1.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        }
        if (!jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString().isEmpty()) {
            jTextField3.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
        }
        jTextField5.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    /*
    検索
     */
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        TeachersLoad slo = new TeachersLoad();
        if (!jTextField1.getText().isEmpty()) {
            slo.setId(Integer.valueOf(jTextField1.getText()));
        }
        slo.setName(jTextField3.getText());
        slo.setKurasu((String) jComboBox1.getSelectedItem());
        Dbstudentinfo db = new Dbstudentinfo();
        List<TeachersLoad> sload = new ArrayList();
//id !null
        if (!jTextField1.getText().isEmpty()) {
            if (slo.getName().isEmpty()) {
                try {
                    //            根据ID从数据库匹配
                    db.getDBcon();
                    sload = db.liketsinfoid(slo.getId());
                    if (sload.isEmpty()) {
                        jLabel6.setText("検索IDなし");
                    } else {
                        db.closeDBcon();
                        jLabel6.setText("検索完了");
//                     if (!sload.isEmpty()) {
                        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
                        tableModel.setRowCount(0);
                        for (TeachersLoad t : sload) {
                            tableModel.addRow(new Object[]{t.getId(), t.getKurasu(), t.getName(), t.getSex(), t.getPassword()});
                        }
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Tstudentinfo.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Tstudentinfo.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                try {
                    //                根据取到的ID和name去数据库匹配
                    db.getDBcon();
                    sload = db.likesinfo(slo.getId(), slo.getName());
                    if (sload.isEmpty()) {
                        jLabel6.setText("検索エラー");
                    } else {
                        db.closeDBcon();
                        jLabel6.setText("検索完了");
//                      if (!sload.isEmpty()) {
                        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
                        tableModel.setRowCount(0);
                        for (TeachersLoad t : sload) {
                            tableModel.addRow(new Object[]{t.getId(), t.getKurasu(), t.getName(), t.getSex(), t.getPassword()});
                        }
//            }

                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Tstudentinfo.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Tstudentinfo.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

//           id null
        } else if (jTextField1.getText().isEmpty()) {
//            name !null
            if (!slo.getName().isEmpty()) {
                try {
                    //              根绝name从数据库
                    db.getDBcon();
                    sload = db.likesinfo(slo.getName());
                    if (sload.isEmpty()) {
                        jLabel6.setText("検索nameなし");
                    } else {
                        db.closeDBcon();
                        jLabel6.setText("検索完了");
//                      if (!sload.isEmpty()) {
                        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
                        tableModel.setRowCount(0);
                        for (TeachersLoad t : sload) {
                            tableModel.addRow(new Object[]{t.getId(), t.getKurasu(), t.getName(), t.getSex(), t.getPassword()});
                        }
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Tstudentinfo.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Tstudentinfo.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                try {
                    //                根据class从数据库
                    db.getDBcon();
                    sload = db.selectstudentkurasu(slo.getKurasu());
                    db.closeDBcon();
                    jLabel6.setText("検索完了");
                    if (!sload.isEmpty()) {
                        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
                        tableModel.setRowCount(0);
                        for (TeachersLoad t : sload) {
                            tableModel.addRow(new Object[]{t.getId(), t.getKurasu(), t.getName(), t.getSex(), t.getPassword()});
                        }
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Tstudentinfo.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Tstudentinfo.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /*
    更新
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TeachersLoad tl = new TeachersLoad();
        List<TeachersLoad> tlo = new ArrayList();
        tl.setId(Integer.valueOf(jTextField1.getText()));
        tl.setName(jTextField3.getText());
        tl.setKurasu((String) jComboBox1.getSelectedItem());
        if (jRadioButton1.isSelected()) {
            tl.setSex(jRadioButton1.getText());
        } else if (!jRadioButton.getHideActionText()) {
            tl.setSex(jRadioButton.getText());
        }
        tl.setPassword(jTextField5.getText());
//        tlo.add(tl);
        Dbstudentinfo db = new Dbstudentinfo();
        try {
            db.getDBcon();
            db.updatestudentinfo(tl);
            db.updateload(tl);
//            db.updateseiseki(tl);
            tlo = db.liketsinfoid(tl.getId());

            if (!tlo.isEmpty()) {
                DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
                tableModel.setRowCount(0);
                for (TeachersLoad t : tlo) {
                    tableModel.addRow(new Object[]{t.getId(), t.getKurasu(), t.getName(), t.getSex(), t.getPassword()});
                    jLabel6.setText("更新完了");
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tstudentinfo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Tstudentinfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        TeachersLoad tload = new TeachersLoad();
        List<TeachersLoad> tlo = new ArrayList();
        if (!jTextField1.getText().isEmpty()) {
            tload.setId(Integer.valueOf(jTextField1.getText()));
        }
        Dbstudentinfo db = new Dbstudentinfo();
        int result;
        try {
            db.getDBcon();
            result = db.selectsinfo(tload.getId());
            if (result == 1) {
                db.deletestudentinfo(tload.getId());
                db.deletelogin(tload.getId());
                db.deleteseiseki(tload.getId());
                db.closeDBcon();
                DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
                tableModel.removeRow(jTable1.getSelectedRow());
                jLabel6.setText("削除しました");
            } else {
                jLabel6.setText("IDユーザーが存在していません");
            }
            tlo = db.liketsinfoid(tload.getId());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tstudentinfo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Tstudentinfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tstudentinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tstudentinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tstudentinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tstudentinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tstudentinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private java.awt.Choice choice1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
